# Generated by Django 2.0.6 on 2018-06-13 15:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
