# Generated by Django 2.0.6 on 2018-06-19 15:38

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180613_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=main.utils.post_image_path, verbose_name='Изображение', width_field='image_width'),
        ),
    ]
