# Generated by Django 2.0.6 on 2018-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20180620_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
