# Generated by Django 2.0.6 on 2018-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('expired_at', models.DateTimeField(verbose_name='Дата и время истечение')),
                ('team', models.ManyToManyField(related_name='event_teams', to='social.Team')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
