# Generated by Django 2.0.6 on 2018-06-28 17:47

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_requestteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='', upload_to=main.utils.team_logo_path, verbose_name='Лого'),
            preserve_default=False,
        ),
    ]
