# Generated by Django 2.0.6 on 2018-07-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='Тип короны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('post_type', models.CharField(choices=[('image', 'Фотографии'), ('video_file', 'Видео')], max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowns', to='social.Post')),
            ],
            options={
                'verbose_name': 'Корона',
                'verbose_name_plural': 'Короны',
            },
        ),
    ]
