# Generated by Django 2.0.6 on 2018-07-01 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_crown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crown',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowns', to='social.Post', unique=True),
        ),
    ]
