# Generated by Django 2.0.6 on 2018-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20180701_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_status',
            field=models.BooleanField(default=True, verbose_name='Разрешение на комментарий'),
        ),
    ]
