# Generated by Django 2.0.6 on 2018-07-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('social', '0018_auto_20180725_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Room'),
        ),
    ]
