# Generated by Django 2.0.6 on 2018-06-13 16:45

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180613_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.avatar_image_path, verbose_name='Изображение'),
        ),
    ]
