# Generated by Django 2.0.6 on 2018-06-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180613_2245'),
        ('accounts', '0002_auto_20180613_2114'),
    ]

    operations = [
    ]
