# Generated by Django 2.0.6 on 2018-06-19 14:53

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20180613_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.wallpaper_image_path, verbose_name='Обои'),
        ),
    ]
